# 1. Build aşaması
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Proje dosyalarını kopyala
COPY ["TourBooking.API.csproj", "./"]
RUN dotnet restore "./TourBooking.API.csproj"

# Tüm kodu kopyala ve publish et
COPY . .
RUN dotnet publish "./TourBooking.API.csproj" -c Release -o /app/publish /p:UseAppHost=false

# 2. Runtime aşaması
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
EXPOSE 8080
EXPOSE 443

# Yayınlanan dosyaları kopyala
COPY --from=build /app/publish .

# Prod ortamında çalıştır
ENTRYPOINT ["dotnet", "TourBooking.API.dll"]
